# Generated by Django 3.0.9 on 2020-11-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0002_auto_20201116_1144"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportingobligation",
            name="rdf_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
