# Generated by Django 3.0.9 on 2020-12-02 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("obligations", "0003_reportingobligation_rdf_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporting_obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="obligations.ReportingObligation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporting_obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="obligations.ReportingObligation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obligation_comment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcceptanceState",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "value",
                    models.CharField(
                        choices=[("Unvalidated", "Unvalidated"), ("Accepted", "Accepted"), ("Rejected", "Rejected")],
                        db_index=True,
                        default="Unvalidated",
                        max_length=20,
                    ),
                ),
                ("probability_model", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("accepted_probability", models.FloatField(blank=True, default=0.0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporting_obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptance_states",
                        to="obligations.ReportingObligation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obligation_acceptance_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user"],
            },
        ),
        migrations.AddConstraint(
            model_name="acceptancestate",
            constraint=models.UniqueConstraint(
                fields=("reporting_obligation_id", "user_id"), name="unique_per_reporting_obligation_and_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptancestate",
            constraint=models.UniqueConstraint(
                fields=("reporting_obligation_id", "probability_model"),
                name="unique_per_reporting_obligation_and_model",
            ),
        ),
    ]
