# Generated by Django 3.0.9 on 2021-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0007_reportingobligation_document_occurs"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportingobligation",
            name="version",
            field=models.CharField(db_index=True, default="initial", max_length=50),
        ),
    ]
