# Generated by Django 3.0.9 on 2021-02-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0008_reportingobligation_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportingobligationoffsets",
            options={"verbose_name_plural": "Reporting Obligation Offsets"},
        ),
    ]
