# Generated by Django 3.0.9 on 2021-02-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0008_reportingobligation_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acceptancestate",
            options={},
        ),
    ]
