# Generated by Django 3.0.9 on 2021-02-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0009_auto_20210217_1005"),
        ("obligations", "0010_auto_20210217_1027"),
    ]

    operations = []
