# Generated by Django 3.0.9 on 2021-02-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0012_auto_20210225_1311"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acceptancestate",
            options={},
        ),
    ]
