# Generated by Django 3.0.9 on 2021-05-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0014_website_filter_rdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingobligation',
            name='rdf_id',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
