# Generated by Django 3.0.3 on 2020-02-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="pull",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="document",
            name="pull",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
