# Generated by Django 3.0.3 on 2020-03-01 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0002_auto_20200229_0605"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
