# Generated by Django 3.0.3 on 2020-03-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0003_auto_20200301_1355"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="author",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="document",
            name="celex",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="document",
            name="eli",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="document",
            name="various",
            field=models.TextField(default=""),
        ),
    ]
