# Generated by Django 3.0.3 on 2020-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0005_auto_20200310_2010"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
