# Generated by Django 3.0.3 on 2020-03-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0006_attachment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="document",
            name="eli",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="document",
            name="various",
            field=models.TextField(blank=True, default=""),
        ),
    ]
