# Generated by Django 3.0.3 on 2020-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0007_auto_20200311_2340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="author",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="document",
            name="celex",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="document",
            name="title_prefix",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
