# Generated by Django 3.0.3 on 2020-04-14 16:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0012_auto_20200403_1212"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50), default=list, size=None
            ),
        ),
    ]
