# Generated by Django 3.0.5 on 2020-04-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0013_auto_20200415_0850"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="accepted_probability",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
