# Generated by Django 3.0.3 on 2020-04-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0013_document_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="tags",
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=50)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="searchapp.Document"
                    ),
                ),
            ],
        ),
    ]
