# Generated by Django 3.0.5 on 2020-04-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0014_document_accepted_probability"),
        ("searchapp", "0014_auto_20200414_1808"),
    ]

    operations = []
