# Generated by Django 3.0.3 on 2020-04-14 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0015_merge_20200415_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptancestate",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="acceptancestate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
