# Generated by Django 3.0.5 on 2020-04-16 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("searchapp", "0018_auto_20200416_1140"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="accepted_probability",
        ),
        migrations.AddField(
            model_name="acceptancestate",
            name="accepted_probability",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name="acceptancestate",
            name="probability_model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="acceptancestate",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
