# Generated by Django 3.0.5 on 2020-05-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0019_auto_20200416_1858"),
    ]

    operations = [
        migrations.RunSQL(
            "DELETE FROM searchapp_acceptancestate WHERE document_id IN (SELECT document_id FROM searchapp_acceptancestate GROUP BY document_id HAVING COUNT(probability_model) > 1)"
        ),
        migrations.AddConstraint(
            model_name="acceptancestate",
            constraint=models.UniqueConstraint(fields=("document_id", "user_id"), name="unique_per_doc_and_user"),
        ),
        migrations.AddConstraint(
            model_name="acceptancestate",
            constraint=models.UniqueConstraint(
                fields=("document_id", "probability_model"), name="unique_per_doc_and_model"
            ),
        ),
    ]
