# Generated by Django 3.0.5 on 2020-05-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0021_auto_20200504_0901"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acceptancestate",
            options={"ordering": ["user"]},
        ),
    ]
