# Generated by Django 3.0.5 on 2020-05-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0022_auto_20200506_1032"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="_acceptance_state_max_probability",
            field=models.FloatField(db_column="acceptance_state_max_probability", default=0.0),
        ),
    ]
