# Generated by Django 3.0.5 on 2020-05-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0023_document__acceptance_state_max_probability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="_acceptance_state_max_probability",
        ),
        migrations.AddField(
            model_name="document",
            name="acceptance_state_max_probability",
            field=models.FloatField(default=0.0),
        ),
    ]
