# Generated by Django 3.0.5 on 2020-05-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0024_auto_20200507_1241"),
        ("searchapp", "0023_auto_20200507_1128"),
    ]

    operations = []
