# Generated by Django 3.0.5 on 2020-06-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0025_merge_20200507_1330"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment",
            old_name="pull",
            new_name="extracted",
        ),
    ]
