# Generated by Django 3.0.5 on 2020-06-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0026_auto_20200605_0949"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extract_text",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="document",
            name="file_url",
            field=models.URLField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
