# Generated by Django 3.0.5 on 2020-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0027_auto_20200605_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_html",
            field=models.TextField(blank=True, default=""),
        ),
    ]
