# Generated by Django 3.0.7 on 2020-06-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0028_document_content_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="consolidated_versions",
            field=models.TextField(blank=True, default=""),
        ),
    ]
