# Generated by Django 3.0.7 on 2020-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0029_document_consolidated_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptancestate",
            name="accepted_probability_index",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
