# Generated by Django 3.0.8 on 2020-07-23 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0030_acceptancestate_accepted_probability_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="content",
        ),
        migrations.RemoveField(
            model_name="document",
            name="content_html",
        ),
        migrations.RemoveField(
            model_name="document",
            name="extract_text",
        ),
        migrations.RemoveField(
            model_name="document",
            name="pull",
        ),
        migrations.AddField(
            model_name="document",
            name="date_last_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
