# Generated by Django 3.0.8 on 2020-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0032_auto_20200728_1134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
