# Generated by Django 3.0.9 on 2020-09-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0035_auto_20200810_0856"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acceptancestate",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="deleted",
        ),
    ]
