# Generated by Django 3.0.9 on 2020-11-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0038_document_formex_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="formex_available",
        ),
    ]
