# Generated by Django 3.0.9 on 2020-11-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0039_remove_document_formex_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="deleted",
        ),
    ]
