# Generated by Django 3.0.9 on 2020-12-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0040_remove_document_deleted"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="acceptancestate",
            constraint=models.CheckConstraint(
                check=models.Q(("user__isnull", False), ("probability_model__isnull", False), _connector="OR"),
                name="searchapp_not_both_null",
            ),
        ),
    ]
