# Generated by Django 3.0.9 on 2020-12-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0042_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="webanno_document_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="webanno_project_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
