# Generated by Django 3.0.9 on 2021-01-05 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0043_auto_20201231_1027"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="date_of_effect",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
