# Generated by Django 3.0.9 on 2021-01-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0044_groups"),
        ("searchapp", "0045_auto_20210105_1001"),
    ]

    operations = []
