# Generated by Django 3.0.9 on 2021-01-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0046_merge_20210115_1401"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="value",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
