# Generated by Django 3.0.9 on 2021-01-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0048_auto_20210115_1540"),
        ("searchapp", "0048_demo_group"),
    ]

    operations = []
