# Generated by Django 3.0.9 on 2021-02-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0049_merge_20210118_1027"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acceptancestate",
            options={},
        ),
    ]
