# Generated by Django 3.0.9 on 2021-02-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0051_auto_20210217_1027"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acceptancestate",
            options={},
        ),
    ]
