# Generated by Django 3.0.9 on 2021-04-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0052_auto_20210225_1311"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="custom_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
