# Generated by Django 3.0.9 on 2021-04-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0053_document_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
