# Generated by Django 3.0.9 on 2021-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0054_auto_20210409_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extract_ro_nlp_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='extract_terms_nlp_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
