# Generated by Django 3.0.5 on 2020-05-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0025_merge_20200507_1330"),
        ("glossary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concept",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="concept",
            name="documents",
            field=models.ManyToManyField(to="searchapp.Document"),
        ),
    ]
