# Generated by Django 3.0.5 on 2020-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0028_document_content_html"),
        ("glossary", "0004_auto_20200616_0840"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="documents",
            field=models.ManyToManyField(blank=True, editable=False, to="searchapp.Document"),
        ),
    ]
