# Generated by Django 3.0.9 on 2020-10-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0005_auto_20200616_1103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
