# Generated by Django 3.0.9 on 2020-11-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0008_auto_20201027_1029"),
        ("glossary", "0008_auto_20201029_0921"),
    ]

    operations = []
