# Generated by Django 3.0.9 on 2020-12-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0009_merge_20201104_1222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="lemma",
            field=models.CharField(db_index=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="concept",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
