# Generated by Django 3.0.9 on 2020-12-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0011_concept_version"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="acceptancestate",
            constraint=models.CheckConstraint(
                check=models.Q(("user__isnull", False), ("probability_model__isnull", False), _connector="OR"),
                name="glossary_not_both_null",
            ),
        ),
    ]
