# Generated by Django 3.0.9 on 2020-12-23 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0041_auto_20201223_1000"),
        ("glossary", "0012_auto_20201223_0959"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="website",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="website", to="searchapp.Website"
            ),
        ),
    ]
