# Generated by Django 3.0.9 on 2021-01-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0014_concept_other"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationworklog",
            name="action",
        ),
        migrations.RemoveField(
            model_name="annotationworklog",
            name="document",
        ),
    ]
