# Generated by Django 3.0.9 on 2021-01-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0015_auto_20210112_1307"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conceptdefined",
            name="unique_per_conceptdefined_and_document",
        ),
        migrations.RemoveConstraint(
            model_name="conceptoccurs",
            name="unique_per_conceptoccurs_and_document",
        ),
        migrations.RemoveField(
            model_name="conceptdefined",
            name="begin",
        ),
        migrations.RemoveField(
            model_name="conceptoccurs",
            name="begin",
        ),
        migrations.AddField(
            model_name="conceptdefined",
            name="endOffset",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="conceptdefined",
            name="quote",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="conceptdefined",
            name="start",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="conceptdefined",
            name="startOffset",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="conceptoccurs",
            name="endOffset",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="conceptoccurs",
            name="quote",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="conceptoccurs",
            name="start",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="conceptoccurs",
            name="startOffset",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="conceptdefined",
            name="end",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="conceptoccurs",
            name="end",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
