# Generated by Django 3.0.9 on 2021-01-14 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0045_auto_20210105_1001"),
        ("glossary", "0016_auto_20210112_1312"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationworklog",
            name="document",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="searchapp.Document"
            ),
            preserve_default=False,
        ),
    ]
