# Generated by Django 3.0.9 on 2021-01-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0045_auto_20210105_1001"),
        ("glossary", "0019_annotationworklog_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationworklog",
            name="document",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="searchapp.Document"),
        ),
    ]
