# Generated by Django 3.0.9 on 2021-02-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0022_auto_20210115_1540"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acceptancestate",
            options={},
        ),
    ]
