# Generated by Django 3.0.9 on 2021-02-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0022_auto_20210115_1540"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lemma",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name="conceptdefined",
            options={"verbose_name_plural": "Concept Definitions"},
        ),
        migrations.AlterModelOptions(
            name="conceptoccurs",
            options={"verbose_name_plural": "Concept Occurances"},
        ),
        migrations.AlterField(
            model_name="concept",
            name="lemma",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="concept",
            name="other",
            field=models.ManyToManyField(blank=True, related_name="_concept_other_+", to="glossary.Concept"),
        ),
        migrations.AddField(
            model_name="concept",
            name="lemma_fk",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="glossary.Lemma"),
        ),
    ]
