# Generated by Django 3.0.9 on 2021-02-17 10:21

from django.db import migrations
import spacy


def lemmatize(term: str, nlp) -> str:
    """
    Lemmatize (multi-word) term using a spacy model.

    :param term: string.
    :return: string.
    """

    lemma = []
    for word in nlp(term):
        lemma.append(word.lemma_)
    term_lemma = " ".join(lemma)
    return term_lemma


def set_lemma_empty(apps, schema_editor):
    nlp = spacy.load("en_core_web_lg")
    Concept = apps.get_model("glossary", "Concept")
    for concept in Concept.objects.filter(lemma=""):
        concept.lemma = lemmatize(concept.name, nlp)
        concept.save()


def set_lemma_fk(apps, schema_editor):
    Concept = apps.get_model("glossary", "Concept")
    Lemma = apps.get_model("glossary", "Lemma")
    for concept in Concept.objects.all():
        lemma = Lemma.objects.update_or_create(name=concept.lemma)
        concept.lemma_fk = lemma[0]
        concept.save()


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0023_auto_20210217_1019"),
    ]

    operations = [migrations.RunPython(set_lemma_empty), migrations.RunPython(set_lemma_fk)]
