# Generated by Django 3.0.9 on 2021-02-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0024_auto_20210217_1021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="lemma_fk",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="concepts", to="glossary.Lemma"
            ),
        ),
    ]
