# Generated by Django 3.0.9 on 2021-02-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0026_merge_20210222_1544"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acceptancestate",
            options={},
        ),
    ]
