# Generated by Django 3.0.9 on 2021-04-07 12:21

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist
import spacy


def lemmatize(term: str, nlp) -> str:
    """
    Lemmatize (multi-word) term using a spacy model.

    :param term: string.
    :return: string.
    """

    lemma = []
    for word in nlp(term.lower()):
        lemma.append(word.lemma_)
    term_lemma = " ".join(lemma)
    return term_lemma


def fix_lemma_case(apps, schema_editor):
    nlp = spacy.load("en_core_web_lg")
    Concept = apps.get_model("glossary", "Concept")
    Lemma = apps.get_model("glossary", "Lemma")

    # Get all Concepts with uppercased lemmas
    for concept in Concept.objects.filter(lemma__regex=r"[A-Z]+"):
        print("WORKING on Concept:" + str(concept))
        # find lowercased lemma
        lemma_lc = Lemma.objects.update_or_create(name=lemmatize(concept.lemma, nlp))[0]
        #  Update concept
        concept.lemma = lemma_lc.name
        concept.lemma_fk = lemma_lc
        concept.save()


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0027_auto_20210225_1311"),
    ]

    operations = [migrations.RunPython(fix_lemma_case)]
