# Generated by Django 3.0.9 on 2021-05-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0028_auto_20210407_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='lemma',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
