# Generated by Django 3.0.9 on 2021-03-23 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DbQuery",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.TextField()),
                (
                    "app",
                    models.CharField(
                        choices=[
                            ("------", "None"),
                            ("glossary", "Glossary"),
                            ("obligations", "Obligations"),
                            ("scheduler", "Scheduler"),
                            ("searchapp", "Searchapp"),
                        ],
                        db_index=True,
                        default="------",
                        max_length=50,
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
