# Generated by Django 3.0.9 on 2021-03-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dblogging", "0001_initial_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbquery",
            name="rdf_query",
            field=models.TextField(default=""),
        ),
    ]
